### ISSUE TITLE
multiple versions of ActionCable / Idiomorph / Stimulus

### ISSUE THREAD

**Issue by KonnorRogers** [hotwired/spark#26]
I noticed Stimulus, ActionCable, and Idiomorph are all getting inlined, which ends up with multiple copies of these libraries.

I imagine this could lead to some unintended behavior and perhaps should be marked external in the rollup config?

Stimulus:

https://github.com/basecamp/hotwire-spark/blob/c8ce327654dc370ce8c217d984e59d6614bad1c0/app/assets/javascripts/hotwire_spark.js#L1394-L1397

ActionCable:

https://github.com/basecamp/hotwire-spark/blob/main/app/assets/javascripts/hotwire_spark.js#L1-L458

Idiomorph:

https://github.com/basecamp/hotwire-spark/blob/c8ce327654dc370ce8c217d984e59d6614bad1c0/app/assets/javascripts/hotwire_spark.js#L552-L553

**Comment by jorgemanrubia** [comment]
Good catch @KonnorRogers. I'll see how to sort out.

**Comment by jorgemanrubia** [comment]
The Stimulus case was handled at https://github.com/hotwired/spark/pull/31 (thanks to @adrienpoly).

I'm not sure idiomorph and Action Cable are big problems to solve. Both dependencies are isolated inside the IIFE of the bundled Javascript. They don't pollute the global space. The only drawback is the payload you may download twice, which I think it's OK since this is a local dev tool.

The Action Cable library can certainly be out of sync with the ActionCable version used in the backend, but I would like to see if that becomes a real problem in practice before declaring that dependency as an external one. My concern is that relying on the user to configure and expose those dependencies properly will worsen the gem setup ergonomy, which is now great. 

I may be missing something here, so please let me know if you have further thoughts.
